### ISSUE TITLE
[legal] create legal contract to embed in 'membership NFT' metadata

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gov#4]

**Comment by julienbrg** [comment]
Can be static (English + French).

Can also be dynamic (configurable) and mention: 

- name of the DAO
- NFT contract address
- DAO contract address
- 'statement of intent' (DAO main objective)
- list of criteria for voting a proposal
- voting rules (as defined in the Governor contract)

**Comment by julienbrg** [comment]
@oscom2 Added a manifesto template with a legal section: https://github.com/julienbrg/signed-sealed-delivered/blob/dev/MANIFESTO.template.md#legal

**Comment by Oscom2** [comment]
Petite overview des problèmes sur lesquels je suis en train de bosser @julienbrg  
J'ai rajouté des petits commentaires à chaque élément qu'on doit inclure dans le manifesto

**I. Mentions obligatoires de statuts de sociétés:** 

- forme de société

DAO = nouvelle forme de société
ou
Modèle d'association avec infrastructure DAO (transparence de data & des in/outflows de capital)

- objet social

PB du cadre fiscal & définit le cadre d'action des dirigeants. 
Ici, cadre fiscal pas clair & pas de dirigeants donc à creuser. Suis pas super calé fiscal faudra que je fasse + de recherches.

- dénomination sociale

Pour le nom, comment authentifier les domaines, peut-être avec un ENS lié à un gnosis safe? 

- siège social

"in the metaverse?" lol

- durée

Techniquement le concept d'une DAO c'est d'être infini. Le max c'est 99ans pour kill les projets inactifs - comment implémenter une clause automatisée? Peut-être mettre une certain durée comme standard, et à la fin de la durée ca auto-exécute un vote de prolongement avec majorité simple? 

- clôture de l exercice social

contexte: obligations comptables etc. Par principe loi 1901, pas d'obligation comptable MAIS pour certaines associations, oui (déterminer pourquoi)
Cependant, ici avec complète transparence des in / out de capital, est-ce nécessaire? peut-être juste créer un tooling de comptabilité permanente et relink vers ca

- capital social

Pareil que au dessus - dashboard de data, relink

- procédure de modification du capital social

pour les apports en numéraire, voir au dessus
pour les apports en nature & industrie + compliqué. Voir comment les retranscrire en format DAO. Peut-être que on peut juste passer par un modèle de token, qui peut être retranscrit en numéraire. Et comme les personnes faisant des apports en nature / industrie recoivent des tokens, leur activité est directement retranscrite en "quantification" numéraire - je sais pas..

- modalité de transmission des actions ou parts sociales

complètement solve avec le système de token

- modalités de direction ou de gérance de la société

ici, parler des formats de gouvernance & clarification de la responsabilisation

- conventions entre la société et ses gérant/dirigeants/associés

Comme au dessus, pas de gérants à part si modèle de "transfert" de droit de vote (comme optimism), ou la question de hostile takeover peut être un pb

- décisions collectives

fix avec modèle DAO + clarification framework gouvernance

- comptes annuels et commissaires aux comptes

Pas nécessaire avec un data dashboard

- affectation et répartition des résultats

le traitement donné aux bénéfices ou pertes générées lors d'un exercice comptable - en gros 1. la distribution de dividendes et 2. le report à nouveau en cas d'exercice bénéficiaire.

Donc pour les boîtes traditionnelles, comme ils centralisent le contrôle, ils peuvent "décider" de l'issuance de fonds pour les associés et participants - sur DAO c'est plus compliqué avec modèle token, car c'est sur le marché ouvert donc modulable en permanence (voir en dessous pour des potentielles solutions mais rien de très concluant pour le moment). 

- dissolution liquidation

Pas clair avec DAO - faudra qu'on travaille le "worst case scenario".
Cependant, techniquement chaque personne peut à tout moment liquider ses parts en vendant le token sur le marché. Donc premier qui vend = premier qui récupère les fonds (modèle un peu malsain). On pourrait réfléchir à un modèle de freeze des DAO operations, avec redistribution équivalente pour "kill" la dao.

**Comment by julienbrg** [comment]
@Oscom2 Thank you so much for your precious inputs we talked about today. I feel like the legal part of the project is a game changer. I'm closing this one. Let's go!!
