### ISSUE TITLE
Add Base network support

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gov#95]
It seems to be testnet-only for now: https://docs.base.org/network-information

cc @bertux

**Comment by julienbrg** [comment]
Both testnet and mainnet

**Comment by bertux** [comment]
that would be nice to be the first to add on Tally a DAO running on Base.

**Comment by julienbrg** [comment]
> that would be nice to be the first to add on Tally a DAO running on Base.

Agreed. Let's just publish an instance of the W3HC there. We could use that dao to do specific tests on Base Testnet. 

@bertux Same seven first members (https://github.com/w3hc/gov/blob/main/scripts/deploy-nft.ts#L16-L24), does that work for you?

**Comment by julienbrg** [comment]
Also related to our upcoming OP stack workshop: https://github.com/orgs/w3hc/projects/2?pane=issue&itemId=29568377

**Comment by julienbrg** [comment]
- Faucets: https://docs.base.org/tools/network-faucets/
- Chainlist: https://chainlist.org/chain/84531
- Docs (Hardhat) https://docs.base.org/guides/deploy-smart-contracts
- Explorer: https://goerli.basescan.org/

## First members

```
const firstMembers = [
    "0x718d0218857f2B6f6e3D171eC3465d7bBf8daD9B",
    "0x466c3c7c3bC3e9153Be21867d73782F02708B45B",
    "0x382AB35697B69a6C08BA86d379583d7f39Fd4941",
    "0x476E2651BF97dE8a26e4A05a9c8e00A6EFa1390c",
    "0x27292E1a901E3E0bE7d144aDba4CAD07da2d8a42",
    "0x5a5dA6353aA78B0f97e69DA11E3ae022df03456e",
    "0x7fd5d090a30460385dd165fc1608e1f66fa2448e"
  ];
```

I would use the same addresses we used to deploy to Gnosis Chain ([Gov](https://gnosisscan.io/address/0xb2d6696f7f006e67b1a1eccb264e0e62a8a76f93#readContract) | [Membership NFT](https://gnosisscan.io/token/0x40e5883fcc5efd3dc72fc50931af4a19f4ac196c))

https://docs.google.com/spreadsheets/d/16N_gcrzh5Bzt7fW7wsketaOsDTry9FWw/edit#gid=364257119

## Mission statement

"We want to build integrations through mentoring and learning."

## DAO Initial config

```
  const name = "Based Hackers"
  const votingDelay = 1
  const votingPeriod = 300
  const votingThreshold = 1
  const quorum = 20
```

I'm not sure about the `votingPeriod` but we can change later if needed. 

I'm ready to deploy. ✅

@bertux @skinito @privatyvesndoutoume @fernandezOli You guys are ok with the first members' list, the mission statement, and the initial DAO config? Let me know if I forgot anything.

**Comment by julienbrg** [comment]
➜ npx hardhat run scripts/deploy-nft.ts --network base-goerli
Compiled 81 Solidity files successfully

Storage in progress...
name: image.png
url: https://bafybeiabub2mlncumqbejfm2seht2lf2pmidcfarb4im6qk32clpusmecm.ipfs.w3s.link/image.png

cid: bafybeiabub2mlncumqbejfm2seht2lf2pmidcfarb4im6qk32clpusmecm
Metadata storage done. ✅ ipfs://bafkreihg4evgww6vgtkbxhwgvdrkhdvxip3dimoott2u7qw2yfb6it2dsy

NFT deployment in progress...

NFT deployed at 0xC1eE76058803FB7741c837F87F5e9CD5de5aFb21 ✅

Block number: 5294119

NFT ABI available in nftAbi.json ✅

Etherscan verification in progress...
Nothing to compile
No need to generate any newer typings.
Successfully submitted source code for contract
contracts/NFT.sol:NFT at 0xC1eE76058803FB7741c837F87F5e9CD5de5aFb21
for verification on the block explorer. Waiting for verification result...

Successfully verified contract NFT on Etherscan.
https://goerli.basescan.org/address/0xC1eE76058803FB7741c837F87F5e9CD5de5aFb21#code
Etherscan verification done. ✅
